export const SELECTED_TRADE = 'SELECTED_TRADE'
export const CONNECT_WALLET = 'CONNECT_WALLET'
export const TRACEORDER_STEP = 'TRACEORDER_STEP'
export const TRACE_TABLELIST = 'TRACE_TABLELIST'
export default SELECTED_TRADE
