export const SELECTED_TRADE = 'SELECTED_TRADE'
export const CONNECT_WALLET = 'CONNECT_WALLET'
export const TRADE_ORDER_STEP = 'TRADE_ORDER_STEP'
export const TRACE_TABLE_LIST = 'TRACE_TABLE_LIST'
export default SELECTED_TRADE
